vector_db:
   index_name: "trading-bot"

embedding_model:
  provider:"google"
  model_name:"models/text-embedding-004"





llm:
  google:
    provider:"google"
    model_name:"gemini-1.5-pro"

  groq:
    provider:"groq"
    model_name:"gemma2-9b-it"


retriever:
  top_K:3
  score_threshold: 0.6

tools:
  tavily:
    max_results:5

